server:
  port: 8989
  
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: sriteja
    password: sriteja
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update